package cn.esileme.model;

import java.util.Date;

public class Fcom {
    private String uname;
    private String image;
    private String fname;
    private String fpic;

    public String getFpic() {
        return fpic;
    }

    public void setFpic(String fpic) {
        this.fpic = fpic;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.cid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.uid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.time
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.fid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.oFid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Integer ofid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.fstar
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private Float fstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fcom.content
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.cid
     *
     * @return the value of fcom.cid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.cid
     *
     * @param cid the value for fcom.cid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.uid
     *
     * @return the value of fcom.uid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.uid
     *
     * @param uid the value for fcom.uid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.time
     *
     * @return the value of fcom.time
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.time
     *
     * @param time the value for fcom.time
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.fid
     *
     * @return the value of fcom.fid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.fid
     *
     * @param fid the value for fcom.fid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.oFid
     *
     * @return the value of fcom.oFid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Integer getOfid() {
        return ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.oFid
     *
     * @param ofid the value for fcom.oFid
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setOfid(Integer ofid) {
        this.ofid = ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.fstar
     *
     * @return the value of fcom.fstar
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public Float getFstar() {
        return fstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.fstar
     *
     * @param fstar the value for fcom.fstar
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setFstar(Float fstar) {
        this.fstar = fstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fcom.content
     *
     * @return the value of fcom.content
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fcom.content
     *
     * @param content the value for fcom.content
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}