package cn.esileme.model;

public class Food {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fname
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.ftitle
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private String ftitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fsales
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private Integer fsales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.content
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.price
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.pprice
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private Float pprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.sid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fpic
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    private String fpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fid
     *
     * @return the value of food.fid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fid
     *
     * @param fid the value for food.fid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fname
     *
     * @return the value of food.fname
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fname
     *
     * @param fname the value for food.fname
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.ftitle
     *
     * @return the value of food.ftitle
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public String getFtitle() {
        return ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.ftitle
     *
     * @param ftitle the value for food.ftitle
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle == null ? null : ftitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fsales
     *
     * @return the value of food.fsales
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public Integer getFsales() {
        return fsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fsales
     *
     * @param fsales the value for food.fsales
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setFsales(Integer fsales) {
        this.fsales = fsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.content
     *
     * @return the value of food.content
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.content
     *
     * @param content the value for food.content
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.price
     *
     * @return the value of food.price
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.price
     *
     * @param price the value for food.price
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.pprice
     *
     * @return the value of food.pprice
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public Float getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.pprice
     *
     * @param pprice the value for food.pprice
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setPprice(Float pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.sid
     *
     * @return the value of food.sid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.sid
     *
     * @param sid the value for food.sid
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fpic
     *
     * @return the value of food.fpic
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public String getFpic() {
        return fpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fpic
     *
     * @param fpic the value for food.fpic
     *
     * @mbggenerated Fri Dec 17 19:50:47 CST 2021
     */
    public void setFpic(String fpic) {
        this.fpic = fpic == null ? null : fpic.trim();
    }
}