package cn.esileme.model;

import java.util.Date;
import java.util.List;

public class Forder {
    private int fsum;

    public int getFsum() {
        return fsum;
    }

    public void setFsum(int fsum) {
        this.fsum = fsum;
    }

    private List<OrderFood> foodList;

    public List<OrderFood> getFoodList() {
        return foodList;
    }

    public void setFoodList(List<OrderFood> foodList) {
        this.foodList = foodList;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.oid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.uid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.sid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.otime
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Date otime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.ono
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private String ono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.ostatus
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Integer ostatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forder.tprice
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    private Float tprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.oid
     *
     * @return the value of forder.oid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.oid
     *
     * @param oid the value for forder.oid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.uid
     *
     * @return the value of forder.uid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.uid
     *
     * @param uid the value for forder.uid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.sid
     *
     * @return the value of forder.sid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.sid
     *
     * @param sid the value for forder.sid
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.otime
     *
     * @return the value of forder.otime
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Date getOtime() {
        return otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.otime
     *
     * @param otime the value for forder.otime
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setOtime(Date otime) {
        this.otime = otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.ono
     *
     * @return the value of forder.ono
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public String getOno() {
        return ono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.ono
     *
     * @param ono the value for forder.ono
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setOno(String ono) {
        this.ono = ono == null ? null : ono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.ostatus
     *
     * @return the value of forder.ostatus
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Integer getOstatus() {
        return ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.ostatus
     *
     * @param ostatus the value for forder.ostatus
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setOstatus(Integer ostatus) {
        this.ostatus = ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forder.tprice
     *
     * @return the value of forder.tprice
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public Float getTprice() {
        return tprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forder.tprice
     *
     * @param tprice the value for forder.tprice
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    public void setTprice(Float tprice) {
        this.tprice = tprice;
    }

    @Override
    public String toString() {
        return "Forder{" +
                "foodList=" + foodList +
                ", oid=" + oid +
                ", uid=" + uid +
                ", sid=" + sid +
                ", otime=" + otime +
                ", ono='" + ono + '\'' +
                ", ostatus=" + ostatus +
                ", tprice=" + tprice +
                '}';
    }
}