package cn.esileme.model;

import org.apache.ibatis.annotations.Select;

import java.util.List;

public class OrderFood {
    private String fname;
    private float price;
    private String fpic;
    private float dfee;
    private String sname;
    private String spic;

    public String getSpic() {
        return spic;
    }

    public void setSpic(String spic) {
        this.spic = spic;
    }

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public float getDfee() {
        return dfee;
    }

    public void setDfee(float dfee) {
        this.dfee = dfee;
    }

    public String getFpic() {
        return fpic;
    }

    public void setFpic(String fpic) {
        this.fpic = fpic;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_food.o_f_id
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    private Integer ofid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_food.oid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_food.fid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_food.fnum
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    private Integer fnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_food.o_f_id
     *
     * @return the value of order_food.o_f_id
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public Integer getoFId() {
        return ofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_food.o_f_id
     *
     * @param oFId the value for order_food.o_f_id
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public void setoFId(Integer oFId) {
        this.ofid = oFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_food.oid
     *
     * @return the value of order_food.oid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_food.oid
     *
     * @param oid the value for order_food.oid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_food.fid
     *
     * @return the value of order_food.fid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_food.fid
     *
     * @param fid the value for order_food.fid
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_food.fnum
     *
     * @return the value of order_food.fnum
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public Integer getFnum() {
        return fnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_food.fnum
     *
     * @param fnum the value for order_food.fnum
     *
     * @mbggenerated Tue Dec 21 08:48:34 CST 2021
     */
    public void setFnum(Integer fnum) {
        this.fnum = fnum;
    }
}