package cn.esileme.model;

public class Pic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.ipic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String ipic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.fid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pid
     *
     * @return the value of pic.pid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pid
     *
     * @param pid the value for pic.pid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic
     *
     * @return the value of pic.pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic
     *
     * @param pic the value for pic.pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.ipic
     *
     * @return the value of pic.ipic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getIpic() {
        return ipic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.ipic
     *
     * @param ipic the value for pic.ipic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setIpic(String ipic) {
        this.ipic = ipic == null ? null : ipic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.fid
     *
     * @return the value of pic.fid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.fid
     *
     * @param fid the value for pic.fid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}