package cn.esileme.model;

public class Skind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skind.kid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Integer kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skind.content
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skind.kid
     *
     * @return the value of skind.kid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skind.kid
     *
     * @param kid the value for skind.kid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skind.content
     *
     * @return the value of skind.content
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skind.content
     *
     * @param content the value for skind.content
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}