package cn.esileme.model;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.sid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.sname
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.concat
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String concat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.site
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.spic
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String spic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.title
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.evaluate
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String evaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.smin
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private Float smin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.dfee
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private Float dfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.kid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private Integer kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.type
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.uid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.sid
     *
     * @return the value of store.sid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.sid
     *
     * @param sid the value for store.sid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.sname
     *
     * @return the value of store.sname
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.sname
     *
     * @param sname the value for store.sname
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.concat
     *
     * @return the value of store.concat
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getConcat() {
        return concat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.concat
     *
     * @param concat the value for store.concat
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setConcat(String concat) {
        this.concat = concat == null ? null : concat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.site
     *
     * @return the value of store.site
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.site
     *
     * @param site the value for store.site
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.spic
     *
     * @return the value of store.spic
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getSpic() {
        return spic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.spic
     *
     * @param spic the value for store.spic
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setSpic(String spic) {
        this.spic = spic == null ? null : spic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.title
     *
     * @return the value of store.title
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.title
     *
     * @param title the value for store.title
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.evaluate
     *
     * @return the value of store.evaluate
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.evaluate
     *
     * @param evaluate the value for store.evaluate
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate == null ? null : evaluate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.smin
     *
     * @return the value of store.smin
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public Float getSmin() {
        return smin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.smin
     *
     * @param smin the value for store.smin
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setSmin(Float smin) {
        this.smin = smin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.dfee
     *
     * @return the value of store.dfee
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public Float getDfee() {
        return dfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.dfee
     *
     * @param dfee the value for store.dfee
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setDfee(Float dfee) {
        this.dfee = dfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.kid
     *
     * @return the value of store.kid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.kid
     *
     * @param kid the value for store.kid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.type
     *
     * @return the value of store.type
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.type
     *
     * @param type the value for store.type
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.uid
     *
     * @return the value of store.uid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.uid
     *
     * @param uid the value for store.uid
     *
     * @mbggenerated Mon Dec 20 20:23:34 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}