package cn.esileme.model;

import org.springframework.web.multipart.MultipartFile;

import java.util.Date;

public class User {
    private MultipartFile imgFile;

    public MultipartFile getImgFile() {
        return imgFile;
    }

    public void setImgFile(MultipartFile imgFile) {
        this.imgFile = imgFile;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.paswd
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String paswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rgtime
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private Date rgtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.image
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.paswd
     *
     * @return the value of user.paswd
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getPaswd() {
        return paswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.paswd
     *
     * @param paswd the value for user.paswd
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setPaswd(String paswd) {
        this.paswd = paswd == null ? null : paswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rgtime
     *
     * @return the value of user.rgtime
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public Date getRgtime() {
        return rgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rgtime
     *
     * @param rgtime the value for user.rgtime
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setRgtime(Date rgtime) {
        this.rgtime = rgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.image
     *
     * @return the value of user.image
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.image
     *
     * @param image the value for user.image
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}