package cn.esileme.mapper;

import cn.esileme.model.Fcom;
import cn.esileme.model.FcomExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface FcomMapper {
    @Select("select fc.*, u.uname, u.image, f.fname, f.fpic from fcom fc " +
            "left join user u on fc.uid = u.uid " +
            "left join order_food fo on fc.oFid = fo.oFid " +
            "left join forder fr on fo.oid = fr.oid " +
            "left join food f on f.fid = fc.fid " +
            "where fr.sid = #{sid}")
    List<Fcom> getEvaList(int sid);

    @Select("select fc.*, u.uname, u.image from fcom fc " +
            "left join user u on fc.uid = u.uid " +
            "where fc.fid = #{fid}")
    List<Fcom> getEvaListByfid(int fid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int countByExample(FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int deleteByExample(FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int insert(Fcom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int insertSelective(Fcom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    List<Fcom> selectByExampleWithBLOBs(FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    List<Fcom> selectByExample(FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    Fcom selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByExampleSelective(@Param("record") Fcom record, @Param("example") FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Fcom record, @Param("example") FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByExample(@Param("record") Fcom record, @Param("example") FcomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByPrimaryKeySelective(Fcom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Fcom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fcom
     *
     * @mbggenerated Wed Dec 22 16:28:36 CST 2021
     */
    int updateByPrimaryKey(Fcom record);
}