package cn.esileme.mapper;

import cn.esileme.model.Forder;
import cn.esileme.model.ForderExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface ForderMapper {
    @Select("select * from forder where oid=#{oid}")
    @Results(
            @Result(property = "foodList", javaType = List.class, column = "oid",
                many = @Many(select = "cn.esileme.mapper.OrderFoodMapper.getFoodList"))
    )
    Forder getOrder(int oid);

    @Select("select * from forder fo " +
            "left join store s on s.sid = fo.sid " +
            "where s.uid=#{uid} and ostatus in (1, 2, 3)")
    @Results(
            @Result(property = "foodList", javaType = List.class, column = "oid",
                many = @Many(select = "cn.esileme.mapper.OrderFoodMapper.getFoodList"))
    )
    List<Forder> getOrderByStoreMan(int uid);

    @Select("select * from forder where uid=#{uid} order by otime desc")
    @Results(
            @Result(property = "foodList", javaType = List.class, column = "oid",
                    many = @Many(select = "cn.esileme.mapper.OrderFoodMapper.getFoodList"))
    )
    List<Forder> getOrderByUid(int uid);

    @Select("select * from forder where uid=#{uid} and ostatus = 4 order by otime desc")
    @Results(
            @Result(property = "foodList", javaType = List.class, column = "oid",
                    many = @Many(select = "cn.esileme.mapper.OrderFoodMapper.getFoodList"))
    )
    List<Forder> evaluateOrder(int uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int countByExample(ForderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int deleteByExample(ForderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int insert(Forder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int insertSelective(Forder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    List<Forder> selectByExample(ForderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    Forder selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Forder record, @Param("example") ForderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int updateByExample(@Param("record") Forder record, @Param("example") ForderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int updateByPrimaryKeySelective(Forder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forder
     *
     * @mbggenerated Tue Dec 21 10:25:22 CST 2021
     */
    int updateByPrimaryKey(Forder record);
}