package cn.esileme.mapper;

import cn.esileme.model.Pic;
import cn.esileme.model.PicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int countByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int deleteByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int insert(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int insertSelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    List<Pic> selectByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    Pic selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") Pic record, @Param("example") PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int updateByExample(@Param("record") Pic record, @Param("example") PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int updateByPrimaryKeySelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbggenerated Fri Dec 17 15:08:45 CST 2021
     */
    int updateByPrimaryKey(Pic record);
}